# Generated by Django 4.2.23 on 2025-10-28 10:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Content status: draft, published, or archived', max_length=20)),
                ('name_en', models.CharField(db_index=True, max_length=200)),
                ('name_ar', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description_en', models.TextField()),
                ('short_description_ar', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('application_icon', models.URLField(blank=True, null=True)),
                ('main_image_en', models.URLField(blank=True, null=True)),
                ('main_image_ar', models.URLField(blank=True, null=True)),
                ('google_play_link', models.URLField(blank=True, null=True)),
                ('app_store_link', models.URLField(blank=True, null=True)),
                ('app_gallery_link', models.URLField(blank=True, null=True)),
                ('screenshots_en', models.JSONField(blank=True, default=list)),
                ('screenshots_ar', models.JSONField(blank=True, default=list)),
                ('avg_rating', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Average rating from 0.00 to 5.00', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('review_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying apps')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('cross_platform', 'Cross Platform')], db_index=True, default='cross_platform', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False, help_text='Whether this app is featured')),
                ('categories', models.ManyToManyField(db_index=True, related_name='apps', to='categories.category')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='developers.developer')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'apps',
                'ordering': ['sort_order', 'name_en'],
                'indexes': [models.Index(fields=['slug'], name='apps_slug_f0e06c_idx'), models.Index(fields=['status'], name='apps_status_ba51b5_idx'), models.Index(fields=['avg_rating'], name='apps_avg_rat_d948ed_idx'), models.Index(fields=['review_count'], name='apps_review__23ff0a_idx'), models.Index(fields=['view_count'], name='apps_view_co_e1fc3d_idx'), models.Index(fields=['featured'], name='apps_feature_fc05f5_idx'), models.Index(fields=['platform'], name='apps_platfor_956401_idx'), models.Index(fields=['sort_order'], name='apps_sort_or_25d029_idx'), models.Index(fields=['developer'], name='apps_develop_9cd82b_idx'), models.Index(fields=['name_en'], name='apps_name_en_317f23_idx'), models.Index(fields=['name_ar'], name='apps_name_ar_4d0798_idx'), models.Index(fields=['status', 'featured'], name='apps_status_e4d7a6_idx')],
            },
        ),
    ]
