# Generated by Django 4.2.23 on 2025-10-28

from django.db import migrations

def create_sample_data(apps, schema_editor):
    """Create sample data for categories, developers, and apps."""
    Category = apps.get_model('categories', 'Category')
    Developer = apps.get_model('developers', 'Developer')
    App = apps.get_model('apps', 'App')

    # Create Islamic category
    category, created = Category.objects.get_or_create(
        name_en='Islamic',
        defaults={
            'name_ar': 'إسلامي',
            'description_en': 'Islamic Applications',
            'description_ar': 'التطبيقات الإسلامية'
        }
    )
    action = "Created" if created else "Found existing"
    print(f"{action} category: {category.name_en} (ID: {category.id})")

    # Create developers
    developers_data = [
        {
            'name_en': 'Tafsir Center for Qur\'anic Studies',
            'name_ar': 'مركز التفسير للدراسات القرآنية',
            'website': 'https://tafsir.app',
            'logo_url': ''
        },
        {
            'name_en': 'Abdullah Bajaber',
            'name_ar': 'عبدالله باجابر',
            'website': '',
            'logo_url': ''
        }
    ]

    created_developers = {}
    for dev_data in developers_data:
        developer, created = Developer.objects.get_or_create(
            name_en=dev_data['name_en'],
            defaults=dev_data
        )
        created_developers[developer.name_en] = developer
        action = "Created" if created else "Found existing"
        print(f"{action} developer: {developer.name_en} (ID: {developer.id})")

    # Create sample apps
    apps_data = [
        {
            'name_en': 'Wahy',
            'name_ar': 'وَحي',
            'slug': '1-wahy',
            'short_description_en': 'Learn Holy Quran word-by-word',
            'short_description_ar': 'القرآن تلاوة وتفسير كلمة بكلمة',
            'description_en': 'Holy Quran app with unique features like Highlight the word being recited, word-translation, repeating ayah in recitation (to help in memorization) and many translations/tafsirs.',
            'description_ar': 'وحي - مصحفك الرقمي المتكامل لتلاوة وفهم واستماع القرآن الكريم بميزات فريدة مثل تمييز الكلمة المقروءة، الترجمة كلمة بكلمة، تكرار الآية في التلاوة (للمساعدة في الحفظ)',
            'status': 'published',
            'application_icon': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/app_icon.png',
            'main_image_en': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/cover_photo_en.png',
            'main_image_ar': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/cover_photo_ar.png',
            'google_play_link': 'https://play.google.com/store/apps/details?id=com.logicdev.quran_reader',
            'app_store_link': 'https://apps.apple.com/sa/app/%D9%88-%D8%AD%D9%8A-%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85/id1615454207',
            'app_gallery_link': 'https://appgallery.huawei.com/#/app/C110460595',
            'screenshots_ar': [
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/01_screenshots_ar.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/02_screenshots_ar.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/03_screenshots_ar.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/04_screenshots_ar.png'
            ],
            'screenshots_en': [
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/01_screenshots_en.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/02_screenshots_en.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/03_screenshots_en.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/04_screenshots_en.png'
            ],
            'developer': created_developers['Tafsir Center for Qur\'anic Studies'],
            'category': category,
        },
        {
            'name_en': 'Ayah',
            'name_ar': 'آية',
            'slug': '15-ayah',
            'short_description_en': 'Quran App',
            'short_description_ar': 'التطبيق الأمثل لقراءة القرآن',
            'description_en': 'Ayah is a modern, fully-featured Quran app that is beautiful and easy to use. Ayah\'s clean, intuitive interface makes for a relaxing reading experience.',
            'description_ar': 'آية تطبيق يوفر تجربة قراءة مريحة بدون أي تشويش بصري. واجهة نظيفة وبديهية تجعل تجربة القراءة مريحة.',
            'status': 'published',
            'application_icon': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/app_icon.png',
            'main_image_en': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/cover_photo_en.png',
            'main_image_ar': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/cover_photo_ar.png',
            'google_play_link': 'https://play.google.com/store/apps/details?id=com.ayah',
            'app_store_link': 'https://apps.apple.com/sa/app/%D8%A2%D9%8A%D8%A9/id706037876',
            'app_gallery_link': 'https://appgallery.huawei.com/app/C101524583',
            'screenshots_ar': [
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/01_screenshots_ar.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/02_screenshots_ar.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/03_screenshots_ar.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/04_screenshots_ar.png'
            ],
            'screenshots_en': [
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/01_screenshots_en.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/02_screenshots_en.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/03_screenshots_en.png',
                'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/04_screenshots_en.png'
            ],
            'developer': created_developers['Abdullah Bajaber'],
            'category': category,
        }
    ]

    for app_data in apps_data:
        # Extract the category and developer from app_data
        category = app_data.pop('category')
        developer = app_data.pop('developer')

        # Try to get existing app
        try:
            app = App.objects.get(slug=app_data['slug'])
            action = "Found existing"
            print(f"{action} app: {app.name_en} (ID: {app.id})")
        except App.DoesNotExist:
            # Create new app with the developer field
            app_data['developer'] = developer
            app = App.objects.create(**app_data)
            app.categories.add(category)
            action = "Created"
            print(f"{action} app: {app.name_en} (ID: {app.id})")

    print(f"\nSummary:")
    print(f"Categories: {Category.objects.count()}")
    print(f"Developers: {Developer.objects.count()}")
    print(f"Apps: {App.objects.count()}")


def reverse_data(apps, schema_editor):
    """Reverse the data population."""
    App = apps.get_model('apps', 'App')
    Category = apps.get_model('categories', 'Category')
    Developer = apps.get_model('developers', 'Developer')

    count = App.objects.count()
    App.objects.all().delete()
    Category.objects.all().delete()
    Developer.objects.all().delete()

    print(f"Deleted {count} apps and all categories/developers")


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('categories', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, reverse_data),
    ]
