# Generated by Django 4.2.25 on 2025-11-12 08:29

from django.db import migrations


def sync_app_categories_from_frontend(apps, schema_editor):
    """
    Sync app categories based on frontend applicationsData.ts file.

    This data migration ensures all apps have the correct category assignments
    as defined in the frontend source of truth.
    """
    App = apps.get_model('apps', 'App')
    Category = apps.get_model('categories', 'Category')

    # App-category mapping extracted from src/app/services/applicationsData.ts
    APP_CATEGORIES_MAP = {
        'Adnan The Quran Teacher': ['kids', 'memorize'],
        'Al Fatiha': ['recite'],
        'Alfanous': ['tools', 'tafsir'],
        'Amazighi Quran': ['riwayat', 'mushaf', 'tafsir', 'translations', 'audio'],
        'Ana Atlou': ['accessibility', 'mushaf', 'tafsir', 'translations'],
        'Ayah': ['mushaf', 'tafsir', 'translations'],
        'Ayah widget': ['tools'],
        'Convey': ['tools'],
        'Ehfaz Al Quran': ['memorize'],
        'Elmohafez': ['memorize', 'mushaf', 'riwayat', 'tafsir', 'translations', 'audio'],
        'Ghareeb': ['tools'],
        'Interactive Tafsir': ['tafsir'],
        'Kaedat Alnoor': ['tajweed'],
        "MA'ANONI DA SHIRIYAR ALQUR'ANI": ['translations', 'mushaf', 'tafsir'],
        'Maher': ['recite', 'mushaf', 'tafsir'],
        'Moddakir': ['recite', 'memorize'],
        'Moeen': ['memorize', 'mushaf'],
        'Mofassal': ['tools', 'memorize'],
        'Mushaf Altdabbor': ['tafsir', 'mushaf'],
        'Mushaf Mecca': ['mushaf', 'riwayat', 'tafsir', 'translations', 'audio'],
        'Noor International Quran': ['translations', 'mushaf', 'audio'],
        'Quran Hafs': ['mushaf', 'tafsir'],
        'Quran Indonesia Kemenag koran': ['translations', 'mushaf', 'tafsir'],
        'Quran Mobasher': ['recite', 'memorize'],
        'Quran Tadabbur': ['tafsir', 'mushaf'],
        'Quran Warsh': ['riwayat', 'mushaf', 'tafsir'],
        'Quranic Recitations Collection': ['audio', 'riwayat', 'translations'],
        'Rayyaan & Bayaan': ['kids', 'memorize'],
        'Salem': ['kids', 'memorize'],
        'Satr': ['tools', 'mushaf'],
        'School Mushaf': ['memorize', 'mushaf', 'kids'],
        'School Mushaf - Sign Language': ['accessibility', 'kids', 'memorize', 'mushaf'],
        'Study Quran': ['tafsir', 'mushaf'],
        'Tangheem Al Quran': ['tajweed'],
        'Tarteel': ['recite', 'memorize', 'translations', 'tafsir'],
        'Tebyan Quran': ['accessibility', 'mushaf', 'tafsir'],
        'Telawa Warsh': ['riwayat', 'mushaf', 'tafsir', 'translations'],
        'The Correct Quotation': ['tools'],
        'The Holy Quran': ['mushaf', 'tools'],
        'Translations of Quran meanings': ['translations'],
        'Wahy': ['mushaf', 'tafsir', 'translations', 'riwayat', 'audio'],
        'Werdy': ['tools'],
        'Wiqaya': ['tajweed', 'mushaf'],
        'Quran': ['mushaf'],  # Generic Quran app gets mushaf category
    }

    updated_count = 0
    notfound_count = 0

    print("\n=== Syncing App Categories from Frontend Data ===")

    for app_name, category_slugs in APP_CATEGORIES_MAP.items():
        try:
            # Find app by English name (case-insensitive exact match)
            app = App.objects.filter(name_en__iexact=app_name).first()

            if not app:
                print(f"  ⚠️  App not found: {app_name}")
                notfound_count += 1
                continue

            # Get category objects
            categories = []
            for slug in category_slugs:
                category = Category.objects.filter(slug=slug).first()
                if category:
                    categories.append(category)
                else:
                    print(f"    ⚠️  Category not found: {slug}")

            if categories:
                # Set categories (replaces existing)
                app.categories.set(categories)

                category_names = ', '.join([c.name_en for c in categories])
                print(f"  ✅ Updated {app.name_en}: {category_names}")
                updated_count += 1

        except Exception as e:
            print(f"  ❌ Error updating {app_name}: {e}")

    # For any apps not in the map, assign default 'mushaf' category
    mapped_app_names = list(APP_CATEGORIES_MAP.keys())
    unmapped_apps = App.objects.exclude(name_en__in=mapped_app_names)

    mushaf_category = Category.objects.filter(slug='mushaf').first()
    if mushaf_category and unmapped_apps.exists():
        for app in unmapped_apps:
            app.categories.set([mushaf_category])
            print(f"  ➡️  Assigned default (mushaf) to: {app.name_en}")
            updated_count += 1

    print(f"\n✅ Sync completed! Updated: {updated_count}, Not found: {notfound_count}\n")


def reverse_sync(apps, schema_editor):
    """
    Reverse migration: assign all apps back to 'Islamic' category.
    """
    App = apps.get_model('apps', 'App')
    Category = apps.get_model('categories', 'Category')

    islamic_category = Category.objects.filter(slug='').first()
    if islamic_category:
        for app in App.objects.all():
            app.categories.set([islamic_category])
        print("Reverted all apps to Islamic category")


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_populate_all_44_apps_with_screenshots'),
        ('categories', '0001_initial'),  # Ensure categories exist
    ]

    operations = [
        migrations.RunPython(sync_app_categories_from_frontend, reverse_sync),
    ]
