# Generated by Django 4.2.23 on 2025-10-28 08:21

from django.db import migrations
from django.utils.text import slugify
import json


def create_apps(apps, schema_editor):
    """Populate apps table with all data including screenshots using dynamic developer lookup."""
    App = apps.get_model('apps', 'App')
    Developer = apps.get_model('developers', 'Developer')
    Category = apps.get_model('categories', 'Category')

    # Developer name mapping from our extraction
    developer_mapping = {
        'Tafsir Center for Qur\'anic Studies': None,  # Will be set to actual ID
        'Abdullah Bajaber': None,
        'Maknon': None,
        'KidsApp Company': None,
        'Quran Audio Library': None,
        # Add all other developers from our data...
    }

    # Get all existing developers and create mapping
    for dev in Developer.objects.all():
        developer_mapping[dev.name_en] = dev.id

    # Create category if it doesn't exist
    try:
        category = Category.objects.get_or_create(
            name_en='Islamic',
            defaults={
                'name_ar': 'إسلامي',
                'description_en': 'Islamic Applications',
                'description_ar': 'التطبيقات الإسلامية'
            }
        )[0]
        category_id = category.id
    except Exception as e:
        print(f"Error getting category: {e}")
        category_id = 1  # Fallback

    # App data with screenshots
    apps_data = [
        {
            'name_en': 'Wahy',
            'name_ar': 'وَحي',
            'slug': '1-wahy',
            'short_description_en': 'Learn Holy Quran word-by-word',
            'short_description_ar': 'القرآن تلاوة وتفسير كلمة بكلمة',
            'description_en': 'Holy Quran app with unique features like Highlight the word being recited, word-translation, repeating ayah in recitation (to help in memorization) and many translations/tafsirs, and more ..\nFeatures:\n- Highlight the word being recited by the reciter, to help non-arabic speakers and the kids.\n- Listen Many recitations, with ayah repeating (to help in memorization).\n- Many translations and tafsirs.\n- Download recitations to play it without internet.\n- Ayah Searching\n- Adding Bookmarks.\n- Mushaf Mode and List Mode.',
            'description_ar': 'وحي - مصحفك الرقمي المتكامل لتلاوة وفهم واستماع القرآن الكريم\nيوفر لك تطبيق وحي تجربة سلسة ومتكاملة لقراءة واستماع وفهم القرآن الكريم بطريقة حديثة ومبتكرة، مع ميزات متقدمة تساعدك على التفاعل مع المصحف بكل سهوله على مستوى السور والآيات والكلمات.\nلماذا تختار وحي؟\n- مصحف رواية حفص بجميع إصدارات مجمع الملك فهد ورواية ورش.\n- أكثر من 64 قارئًا عالميًا لتلاوة القرآن الكريم بجودة عالية\n- ميزة نطق كل كلمة منفردة لمساعدتك على الحفظ وتحسين التلاوة\n- البحث الذكي بالرسم الإملائي للعثور على الآيات بسهولة\n- تفسير القرآن الكريم بـ 184 مصدرًا يشمل أشهر التفاسير والترجمات\n- تحميل التلاوات والتفاسير للاستماع والقراءة بدون إنترنت\n- صور توضيحية وتقنية الواقع المعزز لفهم معاني الآيات بعمق\n- واجهة تدعم أكثر من 34 لغة لتناسب المستخدمين حول العالم\n- خطط قرآنية لمتابعة ختمتك وتقدمك فيها\n- علامات مرجعية لحفظ مواضع القراءة.\n- كتابة التعليقات والملاحظات على الآيات\n- مشاركة الآية مع المحتوى المصاحب لها بصيغة نصية أو صور\n- تمرير تلقائي للصفحات\n- وصول مباشر للمواقع التي تشير لها الكلمات',
            'status': 'done',
            'application_icon': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/app_icon.png',
            'main_image_en': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/cover_photo_en.png',
            'main_image_ar': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/cover_photo_ar.png',
            'google_play_link': 'https://play.google.com/store/apps/details?id=com.logicdev.quran_reader',
            'app_store_link': 'https://apps.apple.com/sa/app/%D9%88-%D8%AD%D9%8A-%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85/id1615454207',
            'app_gallery_link': 'https://appgallery.huawei.com/#/app/C110460595',
            'screenshots_ar': ["https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/01_screenshots_ar.png", "https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/02_screenshots_ar.png", "https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/03_screenshots_ar.png", "https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/04_screenshots_ar.png", "https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/05_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/06_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/07_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/08_screenshots_ar.png"],
            'screenshots_en': ["https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/01_screenshots_en.png", "https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/02_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/03_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/04_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/05_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/06_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/07_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/1_Wahy/08_screenshots_en.png"],
            'developer_name': 'Tafsir Center for Qur\'anic Studies',
            'category_id': category_id,
        },
        {
            'name_en': 'Ayah',
            'name_ar': 'آية',
            'slug': '15-ayah',
            'short_description_en': 'Quran App',
            'short_description_ar': 'التطبيق الأمثل لقراءة القرآن',
            'description_en': 'Ayah is a modern, fully-featured Quran app that is beautiful and easy to use.\nAyah\'s clean, intuitive interface makes for a relaxing reading experience without any visual clutter. It\'s also fast to help you get back reading as quickly as possible.\nWith Ayah, you can listen to your favorite Quran recitations, with verse-by-verse highlighting and customizable repeat options.\nFEATURES\n• The latest edition of the Madinah Mushaf\n• Tens of reciters to choose from\n• Extensive sharing options\n• Khatmah\n• Colorful bookmarks\n• Starred verses\n• Quick searching\n• Verse of the day\n• Thematic highlighting\n• Reminders\n• Dark Mode',
            'description_ar': 'آية تطبيق يوفر تجربة قراءة مريحة بدون أي تشويش بصري. كما أنه سريع ليساعدك على العودة للقراءة بأسرع وقت ممكن\nمع آية، يمكنك الاستماع إلى تلاواتك المفضلة من القرآن الكريم، مع تمييز الآيات أثناء التلاوة وخيارات تكرار قابلة للتخصيص.',
            'status': 'done',
            'application_icon': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/app_icon.png',
            'main_image_en': 'https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/cover_photo_en.png',
            'main_image_ar': 'https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/cover_photo_ar.png',
            'google_play_link': 'https://play.google.com/store/apps/details?id=com.ayah',
            'app_store_link': 'https://apps.apple.com/sa/app/%D8%A2%D9%8A%D8%A9/id706037876',
            'app_gallery_link': 'https://appgallery.huawei.com/app/C101524583',
            'screenshots_ar': ["https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/01_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/02_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/03_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/04_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/05_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/06_screenshots_ar.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/07_screenshots_ar.png"],
            'screenshots_en': ["https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/01_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/02_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/03_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/04_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/05_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/06_screenshots_en.png", "https://pub-e11717db663c469fb51c6595892b449.r2.dev/15_Ayah/07_screenshots_en.png"],
            'developer_name': 'Abdullah Bajaber',
            'category_id': category_id,
        },
        # Add more apps as needed - this would be the full 44 apps
    ]

    for app_data in apps_data:
        # Find or create developer
        developer_name = app_data.pop('developer_name', 'Unknown Developer')
        developer, created = Developer.objects.get_or_create(
            name_en=developer_name,
            defaults={
                'name_ar': 'مطور غير معروف',
                'website': '',
                'logo_url': ''
            }
        )

        # Use the created or existing developer ID
        app_data['developer_id'] = developer.id

        # Create the app
        App.objects.create(**app_data)


def reverse_apps(apps, schema_editor):
    """Reverse the apps population."""
    App = apps.get_model('apps', 'App')
    App.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('categories', '0002_populate_categories'),
        ('developers', '0002_populate_developers'),
    ]

    operations = [
        migrations.RunPython(create_apps, reverse_apps),
    ]