# Generated by Django 4.2.25 on 2025-11-12 10:38

from django.db import migrations


def remove_islamic_category(apps, schema_editor):
    """Remove Islamic category to match frontend applicationsData.ts"""
    Category = apps.get_model('apps', 'Category')

    # Delete the Islamic category
    islamic_category = Category.objects.filter(name_en='Islamic').first()
    if islamic_category:
        print(f"Removing Islamic category (ID: {islamic_category.id})")
        # First, unassign this category from all apps
        islamic_category.app_set.clear()
        # Then delete the category
        islamic_category.delete()
        print("Islamic category removed successfully")
    else:
        print("Islamic category not found")


def revert_remove_islamic_category(apps, schema_editor):
    """Restore Islamic category if needed"""
    Category = apps.get_model('apps', 'Category')

    # Check if Islamic category exists
    if not Category.objects.filter(name_en='Islamic').exists():
        Category.objects.create(
            name_en='Islamic',
            name_ar='إسلامي',
            slug='',
            description_en='Islamic Applications',
            description_ar='التطبيقات الإسلامية',
            icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#A0533B" d="M3.75 3.75v4.5h4.5v-4.5zm-2.25 0A2.25 2.25 0 0 1 3.75 1.5h4.5a2.25 2.25 0 0 1 2.25 2.25v4.5a2.25 2.25 0 0 1-2.25 2.25h-4.5A2.25 2.25 0 0 1 1.5 8.25zm2.25 12v4.5h4.5v-4.5zm-2.25 0a2.25 2.25 0 0 1 2.25-2.25h4.5a2.25 2.25 0 0 1 2.25 2.25v4.5a2.25 2.25 0 0 1-2.25 2.25h-4.5a2.25 2.25 0 0 1-2.25-2.25zm18.75-12h-4.5v4.5h4.5zm-4.5-2.25h4.5a2.25 2.25 0 0 1 2.25 2.25v4.5a2.25 2.25 0 0 1-2.25 2.25h-4.5a2.25 2.25 0 0 1-2.25-2.25v-4.5a2.25 2.25 0 0 1 2.25-2.25m0 14.25v4.5h4.5v-4.5zm-2.25 0a2.25 2.25 0 0 1 2.25-2.25h4.5a2.25 2.25 0 0 1 2.25 2.25v4.5a2.25 2.25 0 0 1-2.25 2.25h-4.5a2.25 2.25 0 0 1-2.25-2.25z"/></svg>'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_sync_app_categories_from_frontend'),
    ]

    operations = [
        migrations.RunPython(remove_islamic_category, revert_remove_islamic_category),
    ]
