# Generated by Django 4.2.23 on 2025-12-14 12:55

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_setup_pgvector_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
