# Generated by Django 4.2.23 on 2025-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_change_embedding_dimensions_to_gemini'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='crawled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when external content was last crawled', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='crawled_content',
            field=models.TextField(blank=True, help_text='Cached content crawled from external sources (Google Play, App Store, AppGallery)', null=True),
        ),
    ]
