# Generated by Django 4.2.23 on 2026-01-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_fix_broken_developer_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppViewEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the view occurred')),
                ('referrer', models.URLField(blank=True, help_text='HTTP Referer header', max_length=2000, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent string', null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Session identifier for deduplication', max_length=64, null=True)),
                ('country_code', models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 country code from Cloudflare', max_length=2, null=True)),
                ('ip_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of IP with daily rotating salt', max_length=64, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('bot', 'Bot'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Device type: mobile, tablet, desktop, bot, unknown', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100, null=True)),
                ('os', models.CharField(blank=True, help_text='Operating system name and version', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'App View Event',
                'verbose_name_plural': 'App View Events',
                'db_table': 'app_view_events',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='appcrawleddata',
            new_name='app_crawled_app_id_41ff86_idx',
            old_name='app_crawled_app_id_0d5c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='appcrawleddata',
            new_name='app_crawled_status_2187f8_idx',
            old_name='app_crawled_status_5e6e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='appcrawleddata',
            new_name='app_crawled_crawled_81d9e8_idx',
            old_name='app_crawled_crawled_6f7c2e_idx',
        ),
        migrations.AddField(
            model_name='appviewevent',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='apps.app'),
        ),
        migrations.AddIndex(
            model_name='appviewevent',
            index=models.Index(fields=['app', 'viewed_at'], name='app_view_ev_app_id_2f56b3_idx'),
        ),
        migrations.AddIndex(
            model_name='appviewevent',
            index=models.Index(fields=['viewed_at', 'app'], name='app_view_ev_viewed__ece51f_idx'),
        ),
        migrations.AddIndex(
            model_name='appviewevent',
            index=models.Index(fields=['app', 'country_code'], name='app_view_ev_app_id_7a409e_idx'),
        ),
        migrations.AddIndex(
            model_name='appviewevent',
            index=models.Index(fields=['app', 'device_type'], name='app_view_ev_app_id_d5a151_idx'),
        ),
    ]
