# Generated by Django for Multi-Filter API Support
# Migration 0020: Add riwayah, mushaf_type, and features fields with GIN indexes

from django.db import migrations, models
import django.contrib.postgres.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_make_main_images_mandatory'),
    ]

    operations = [
        # Add riwayah field (JSONField for multi-select)
        migrations.AddField(
            model_name='app',
            name='riwayah',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of supported Quranic riwayat (recitation styles). Valid values: hafs, warsh, qalun, shubah, alduri, alsusi, hisham, ibn_dhakwan, khalaf, khallad, other'
            ),
        ),
        # Add mushaf_type field (JSONField for multi-select)
        migrations.AddField(
            model_name='app',
            name='mushaf_type',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of supported Mushaf types. Valid values: madani, uthmani, indo_pak, moroccan, simple, tajweed, other'
            ),
        ),
        # Add features field (JSONField for multi-select)
        migrations.AddField(
            model_name='app',
            name='features',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of app features. Valid values: offline, audio, translation, tafsir, bookmarks, search, tajweed, dark_mode, memorization, prayer_times, qibla, notifications'
            ),
        ),
        # Add GIN index for riwayah field
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['riwayah'],
                name='apps_riwayah_gin'
            ),
        ),
        # Add GIN index for mushaf_type field
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['mushaf_type'],
                name='apps_mushaf_type_gin'
            ),
        ),
        # Add GIN index for features field
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['features'],
                name='apps_features_gin'
            ),
        ),
    ]
