# Pre-commit hooks configuration for Quran Apps Directory Backend
# Install: pre-commit install
# Run manually: pre-commit run --all-files
# Update hooks: pre-commit autoupdate

default_language_version:
  python: python3.9

repos:
  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3.9
        args: ['--line-length=100']

  # Import sorting with isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']

  # Linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: ['--fix', '--line-length=100']

  # Flake8 linting (additional checks)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--ignore=E203,W503']
        additional_dependencies: ['flake8-docstrings', 'flake8-bugbear']

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--no-strict-optional']
        additional_dependencies: ['types-all']
        exclude: '(migrations/|venv/)'

  # YAML validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-template={original}']
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: '(tests/|migrations/)'
        args: ['-ll']  # Only report medium and high severity

  # Docstring coverage
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ['--vv', '--fail-under=75', '--ignore-init-method', '--ignore-init-module']
        exclude: '(tests/|migrations/|venv/)'

# Configuration for specific tools (prefer pyproject.toml):
# - Black: configured in pyproject.toml
# - isort: configured in pyproject.toml
# - mypy: configured in pyproject.toml
# - pytest: configured in pyproject.toml
