release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: gunicorn --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --timeout 30 --access-logfile - --error-logfile - config.wsgi:application
