# Generated by Django 4.2.23 on 2025-11-26 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0003_sync_app_categories_from_frontend'),
        ('categories', '0005_rename_tools_to_other_and_reorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.CharField(db_index=True, default=submissions.models.generate_tracking_id, help_text='Unique tracking ID for the submission (e.g., QAD-ABC123)', max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('info_requested', 'Information Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitter_name', models.CharField(max_length=200)),
                ('submitter_email', models.EmailField(db_index=True, max_length=254)),
                ('submitter_phone', models.CharField(blank=True, max_length=50)),
                ('submitter_organization', models.CharField(blank=True, max_length=200)),
                ('is_developer', models.BooleanField(default=False, help_text='Whether the submitter is the developer/owner of the app')),
                ('app_name_en', models.CharField(db_index=True, max_length=200)),
                ('app_name_ar', models.CharField(db_index=True, max_length=200)),
                ('short_description_en', models.TextField(help_text='Brief description in English (max 150 chars)', max_length=150)),
                ('short_description_ar', models.TextField(help_text='Brief description in Arabic (max 150 chars)', max_length=150)),
                ('description_en', models.TextField(blank=True, help_text='Full description in English')),
                ('description_ar', models.TextField(blank=True, help_text='Full description in Arabic')),
                ('google_play_link', models.URLField(blank=True)),
                ('app_store_link', models.URLField(blank=True)),
                ('app_gallery_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
                ('developer_name_en', models.CharField(max_length=200)),
                ('developer_name_ar', models.CharField(blank=True, max_length=200)),
                ('developer_website', models.URLField(blank=True)),
                ('developer_email', models.EmailField(blank=True, max_length=254)),
                ('app_icon_url', models.URLField(blank=True)),
                ('screenshots_en', models.JSONField(blank=True, default=list, help_text='List of English screenshot URLs')),
                ('screenshots_ar', models.JSONField(blank=True, default=list, help_text='List of Arabic screenshot URLs')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional information from the submitter')),
                ('content_confirmation', models.BooleanField(default=False, help_text="Submitter confirmed content doesn't violate guidelines")),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to submitter)')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (sent to submitter)')),
                ('info_request_message', models.TextField(blank=True, help_text='Message requesting additional information')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='submissions', to='categories.category')),
                ('created_app', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='apps.app')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Submission',
                'verbose_name_plural': 'App Submissions',
                'db_table': 'app_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('info_requested', 'Information Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('info_requested', 'Information Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='submissions.appsubmission')),
            ],
            options={
                'verbose_name': 'Status Log',
                'verbose_name_plural': 'Status Logs',
                'db_table': 'submission_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appsubmission',
            index=models.Index(fields=['tracking_id'], name='app_submiss_trackin_205aac_idx'),
        ),
        migrations.AddIndex(
            model_name='appsubmission',
            index=models.Index(fields=['status'], name='app_submiss_status_cd6dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='appsubmission',
            index=models.Index(fields=['submitter_email'], name='app_submiss_submitt_e49fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='appsubmission',
            index=models.Index(fields=['status', 'created_at'], name='app_submiss_status_2ca4aa_idx'),
        ),
    ]
