# Generated by Django 4.2.23 on 2025-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsubmission',
            name='main_image_ar',
            field=models.URLField(blank=True, help_text='Main cover image URL for Arabic listing'),
        ),
        migrations.AddField(
            model_name='appsubmission',
            name='main_image_en',
            field=models.URLField(blank=True, help_text='Main cover image URL for English listing'),
        ),
    ]
