# Generated by Django 4.2.23 on 2025-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.URLField(blank=True, help_text='Icon URL for the category', null=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code for the category', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name_en'],
                'indexes': [models.Index(fields=['slug'], name='categories_slug_b4303a_idx'), models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'), models.Index(fields=['sort_order'], name='categories_sort_or_77e69f_idx')],
            },
        ),
    ]
