# Generated by Django 4.2.23 on 2025-10-28 08:21

from django.db import migrations


def create_categories(apps, schema_editor):
    """Populate categories table."""
    Category = apps.get_model('categories', 'Category')

    categories_data = [
        {
            'name_en': 'Islamic',
            'name_ar': 'إسلامي',
            'description_en': 'Islamic Applications',
            'description_ar': 'التطبيقات الإسلامية',
        },
    ]

    for cat_data in categories_data:
        Category.objects.create(**cat_data)


def reverse_categories(apps, schema_editor):
    """Reverse the categories population."""
    Category = apps.get_model('categories', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_categories),
    ]
