# Generated by Django 4.2.25 on 2025-11-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_islamic_category'),
    ]

    operations = [
    ]
