# Generated by Django 4.2.25 on 2025-11-12 10:52

from django.db import migrations


def update_category_sort_orders(apps, schema_editor):
    """Update category sort orders to match UI layout from images"""
    Category = apps.get_model('categories', 'Category')

    # Define the desired order based on the UI images
    category_order = [
        ('mushaf', 1),
        ('translations', 2),
        ('recite', 3),
        ('kids', 4),
        ('tafsir', 5),
        ('riwayat', 6),
        ('audio', 7),
        ('memorize', 8),
        ('tajweed', 9),
        ('accessibility', 10),
        ('tools', 11),
    ]

    for slug, sort_order in category_order:
        category = Category.objects.filter(slug=slug).first()
        if category:
            category.sort_order = sort_order
            category.save(update_fields=['sort_order'])
            print(f"Updated {category.name_en} sort_order to {sort_order}")
        else:
            print(f"Warning: Category with slug '{slug}' not found")


def revert_category_sort_orders(apps, schema_editor):
    """Revert to previous sort orders"""
    Category = apps.get_model('categories', 'Category')

    # Reset to default (0) or previous values
    # This is a simple revert - original sort orders can be restored if needed
    for category in Category.objects.all():
        category.sort_order = 0
        category.save(update_fields=['sort_order'])
    print("Reset all category sort_orders to 0")


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_update_category_sort_orders'),
    ]

    operations = [
        migrations.RunPython(update_category_sort_orders, revert_category_sort_orders),
    ]
