# Generated by Django 4.2.25 on 2025-11-12 10:54

from django.db import migrations


def rename_tools_and_reorder(apps, schema_editor):
    """Rename Tools to Other and update category sort orders to match UI"""
    Category = apps.get_model('categories', 'Category')

    # Rename Tools to Other
    tools_category = Category.objects.filter(slug='tools').first()
    if tools_category:
        tools_category.name_en = 'Other'
        tools_category.name_ar = 'أخرى'
        tools_category.save(update_fields=['name_en', 'name_ar'])
        print(f"Renamed 'Tools' to 'Other'")

    # Define the correct order based on the UI images
    category_order = [
        ('mushaf', 1),
        ('translations', 2),
        ('recite', 3),
        ('kids', 4),
        ('tafsir', 5),
        ('riwayat', 6),
        ('audio', 7),
        ('memorize', 8),
        ('tajweed', 9),
        ('accessibility', 10),
        ('tools', 11),  # Now "Other" category
    ]

    for slug, sort_order in category_order:
        category = Category.objects.filter(slug=slug).first()
        if category:
            category.sort_order = sort_order
            category.save(update_fields=['sort_order'])
            print(f"Updated {category.name_en} sort_order to {sort_order}")
        else:
            print(f"Warning: Category with slug '{slug}' not found")


def revert_rename_and_reorder(apps, schema_editor):
    """Revert Tools name and reset sort orders"""
    Category = apps.get_model('categories', 'Category')

    # Rename Other back to Tools
    other_category = Category.objects.filter(slug='tools').first()
    if other_category:
        other_category.name_en = 'Tools'
        other_category.name_ar = 'أدوات'
        other_category.save(update_fields=['name_en', 'name_ar'])

    # Reset sort orders
    for category in Category.objects.all():
        category.sort_order = 0
        category.save(update_fields=['sort_order'])
    print("Reverted category names and sort orders")


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_update_category_sort_order'),
    ]

    operations = [
        migrations.RunPython(rename_tools_and_reorder, revert_rename_and_reorder),
    ]
