# Generated by Django 4.2.25 on 2025-10-19 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=200, unique=True)),
                ('name_ar', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_url', models.URLField(blank=True, help_text='Developer/company logo URL', null=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Additional contact information')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether this developer is verified')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links')),
            ],
            options={
                'db_table': 'developers',
                'ordering': ['name_en'],
                'indexes': [models.Index(fields=['name_en'], name='developers_name_en_22cd99_idx'), models.Index(fields=['is_verified'], name='developers_is_veri_8653ef_idx')],
            },
        ),
    ]
