# Generated by Django 4.2.23 on 2025-10-28 08:21

from django.db import migrations


def create_developers(apps, schema_editor):
    """Populate developers table."""
    Developer = apps.get_model('developers', 'Developer')

    developers_data = [
        {
            'name_en': 'Tafsir Center for Qur\'anic Studies',
            'name_ar': 'مركز تفسير للدراسات القرآنية',
            'website': 'https://tafsir.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/1_Wahy/developer_logo.png',
        },
        {
            'name_en': 'Abdullah Bajaber',
            'name_ar': 'عبدالله باجابر',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/15_Ayah/developer_logo.Not Found',
        },
        {
            'name_en': 'Maknon',
            'name_ar': 'مكنون',
            'website': 'https://maknon.org.sa',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/14_Quran Mobasher/developer_logo.png',
        },
        {
            'name_en': 'KidsApp Company',
            'name_ar': 'شركة تطبيقات الطفولة',
            'website': 'https://kidsapp.sa',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/10_Adnan The Quran Teacher/developer_logo.png',
        },
        {
            'name_en': 'Quran Audio Library',
            'name_ar': 'المكتبة الصوتية للقرآن الكريم',
            'website': 'https://mp3quran.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/17_Al Fatiha/developer_logo.png',
        },
        {
            'name_en': 'Quran.com',
            'name_ar': 'Quran.com',
            'website': 'https://quran.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/5_Quran/developer_logo.png',
        },
        {
            'name_en': 'Malem Altdabbor',
            'name_ar': 'معالم التدبر',
            'website': 'https://tadabbor.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/36_Mushaf Altdabbor/developer_logo.png',
        },
        {
            'name_en': 'Tarteel, Inc',
            'name_ar': 'شركة ترتيل',
            'website': 'https://www.tarteel.ai',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/11_Tarteel/developer_logo.png',
        },
        {
            'name_en': 'Badr Alhanaky',
            'name_ar': 'بدر الحناكي',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/39_Ayah widget/developer_logo.Not Found',
        },
        {
            'name_en': 'Mushaf Makkah',
            'name_ar': 'مصحف مكة',
            'website': 'https://mushafmakkah.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/48_Mushaf Mecca/developer_logo.png',
        },
        {
            'name_en': 'AL BORHAN CHARITY FOR SUNNAH & QURAN SERVICES',
            'name_ar': 'جمعية البرهان لخدمة السنة والقرآن',
            'website': 'https://www.alborhan.sa',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/9_Maher/developer_logo.png',
        },
        {
            'name_en': 'elMohafez',
            'name_ar': 'محفظ الوحيين',
            'website': 'https://www.elmohafez.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/49_Elmohafez/developer_logo.svg',
        },
        {
            'name_en': 'Moddakir',
            'name_ar': 'مدكر',
            'website': 'https://moddakir.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/7_Moddakir/developer_logo.png',
        },
        {
            'name_en': 'Basayir',
            'name_ar': 'وقف بصائر لخدمة القرآن الكريم وعلومه',
            'website': 'https://basayir.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/38_MA\'ANONI DA SHIRIYAR ALQUR\'ANI/developer_logo.png',
        },
        {
            'name_en': 'Ministry of Islamic Affairs, Dawah and Guidance',
            'name_ar': 'وزارة الشؤون الإسلامية والدعوة والإرشاد',
            'website': 'https://www.moia.gov.sa',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/51_The Correct Quotation/developer_logo.png',
        },
        {
            'name_en': 'Digital Corners',
            'name_ar': 'شركة الأركان الرقمية',
            'website': 'https://digital-corners.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/52_Satr/developer_logo.png',
        },
        {
            'name_en': 'Faisal Haddad',
            'name_ar': 'فيصل حداد',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/53_Moeen/developer_logo.Not Found',
        },
        {
            'name_en': 'Almenhaj Center for Educational Supervision and training',
            'name_ar': 'مركز المنهاج للإشراف والتدريب التربوي',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/80_Quran Tadabbur/developer_logo.jpg',
        },
        {
            'name_en': 'The Noble Qur\'an Encyclopedia',
            'name_ar': 'موسوعة القرآن الكريم',
            'website': 'https://quranenc.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/69_Translations of Quran meanings/developer_logo.svg',
        },
        {
            'name_en': 'Noor Taibah Foundation',
            'name_ar': 'مؤسسة نور طيبة',
            'website': 'https://noortaibah.org',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/54_Ana Atlou/developer_logo.svg',
        },
        {
            'name_en': 'Islam phone',
            'name_ar': 'إسلام فون',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/55_Alfanous/developer_logo.png',
        },
        {
            'name_en': 'Noor International',
            'name_ar': 'نور انترناشونال',
            'website': 'https://noorinternational.net/ar',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/57_Noor International Quran/developer_logo.png',
        },
        {
            'name_en': 'Arabia IT',
            'name_ar': 'شركة الدار العربية',
            'website': 'https://arabia-it.com/',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/58_Werdy/developer_logo.png',
        },
        {
            'name_en': 'Nuqayah',
            'name_ar': 'نُقاية',
            'website': 'https://nuqayah.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/37_Interactive Tafsir/developer_logo.svg',
        },
        {
            'name_en': 'Arabic IT',
            'name_ar': 'الدار العربية',
            'website': 'https://arabia-it.com/',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/60_School Mushaf - Sign Language/developer_logo.png',
        },
        {
            'name_en': 'King Fahd Glorious Quran Printing Complex',
            'name_ar': 'مجمع الملك فهد لطباعة المصحف الشريف',
            'website': 'https://qurancomplex.gov.sa/',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/23_Quran Hafs/developer_logo.png',
        },
        {
            'name_en': 'مؤسسة تأثير للنشر',
            'name_ar': 'مؤسسة تأثير للنشر',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/65_Tangheem Al Quran/developer_logo.png',
        },
        {
            'name_en': 'Liajlehum',
            'name_ar': 'جمعية لأجلهم لخدمة الأشخاص ذوي الإعاقة',
            'website': 'https://www.liajlehum.org.sa',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/56_Tebyan Quran/developer_logo.Not Found',
        },
        {
            'name_en': 'Quranic Recitations Collection',
            'name_ar': 'جامع التلاوات القرآنية',
            'website': 'https://zekr.online',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/70_Quranic Recitations Collection/developer_logo.Not Found',
        },
        {
            'name_en': 'Jabal Al-Noor Scientific Complex in Makkah',
            'name_ar': 'مجمع جبل النور العلمي بمكة المكرمة',
            'website': '',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/64_Kaedat Alnoor/developer_logo.jpg',
        },
        {
            'name_en': 'Qaf Group for Research, Translation, Publication, and IT Solutions',
            'name_ar': 'مجموعة قاف للدراسات والترجمة والتقنية والنشر',
            'website': 'https://www.qafgroup.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/82_Quran Indonesia Kemenag koran/developer_logo.svg',
        },
        {
            'name_en': 'Noor International',
            'name_ar': 'نور إنترناشيونال',
            'website': 'https://noorinternational.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/47_Convey/developer_logo.png',
        },
        {
            'name_en': 'Wiqaya',
            'name_ar': 'وقاية اللسان',
            'website': 'https://wiqayah.net',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/63_Wiqaya/developer_logo.Not Found',
        },
        {
            'name_en': 'مؤسسة النبأ العظيم',
            'name_ar': 'مؤسسة النبأ العظيم',
            'website': 'https://alnpaa.com',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/35_Study Quran/developer_logo.png',
        },
        {
            'name_en': 'Ealamy group',
            'name_ar': 'شركة إعلامي',
            'website': 'https://ealamy.com/',
            'logo_url': 'https://pub-e11717db663c469fb51c65995892b449.r2.dev/61_Ehfaz Al Quran/developer_logo.png',
        },
    ]

    for dev_data in developers_data:
        Developer.objects.create(**dev_data)


def reverse_developers(apps, schema_editor):
    """Reverse the developers population."""
    Developer = apps.get_model('developers', 'Developer')
    Developer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_developers, reverse_developers),
    ]
